# config/kratos/kratos.yml
dsn: postgres://userms:userms_password@postgres:5432/userms?sslmode=disable

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:3001
        - http://172.16.1.65:3000
        - http://172.16.1.65:3001
        - http://localhost:8080
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - X-Requested-With
        - Accept
        - Origin
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:3001/
  allowed_return_urls:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3000/auth/callback
    - http://localhost:3001/auth/callback
    - http://172.16.1.65:3000
    - http://172.16.1.65:3001
    - http://172.16.1.65:3000/auth/callback
    - http://172.16.1.65:3001/auth/callback

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: 165106799463-ijl47hp8fco7abh6hcsu453lb4kvqjlf.apps.googleusercontent.com
            client_secret: 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
            mapper_url: file:///etc/config/kratos/google_mapper.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name: null
    code:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:3001/error

    settings:
      ui_url: http://localhost:3001/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://localhost:3001/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://localhost:3001/verification
      use: code
      lifespan: 30m
      after:
        default_browser_return_url: http://localhost:3001/

    logout:
      after:
        default_browser_return_url: http://localhost:3001/login

    login:
      ui_url: http://localhost:3001/login
      lifespan: 10m
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://backend:3000/hooks/after-login
              method: POST
              body: file:///etc/config/kratos/webhook_body.jsonnet

    registration:
      lifespan: 10m
      ui_url: http://localhost:3001/register
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://backend:3000/hooks/after-registration
                method: POST
                body: file:///etc/config/kratos/webhook_body.jsonnet
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://backend:3000/hooks/after-registration
                method: POST
                body: file:///etc/config/kratos/webhook_body.jsonnet
            - hook: session
            # REMOVED show_verification_ui for OAuth - Google users are auto-verified

log:
  level: info
  format: text
  leak_sensitive_values: false

secrets:
  cookie:
    - "f8h3x9nR7mQ2vL6bK1sD8wE4yP5tA9zN"
  cipher:
    - "k7nH2vL8bF5sQ1wE9tY6pA3mR4xN7zD0"

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
