services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: userms
      POSTGRES_USER: userms
      POSTGRES_PASSWORD: userms_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/001_initial_schema.sql
      - ./migrations/002_add_oauth2_tables.sql:/docker-entrypoint-initdb.d/002_add_oauth2_tables.sql
    networks:
      - intranet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userms -d userms"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kratos database
  kratos-postgres:
    image: postgres:15-alpine
    container_name: userms-kratos-postgres
    environment:
      POSTGRES_DB: kratos
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: kratos_password
    volumes:
      - kratos_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - intranet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kratos -d kratos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NEW: Hydra database
  hydra-postgres:
    image: postgres:15-alpine
    container_name: userms-hydra-postgres
    environment:
      POSTGRES_DB: hydra
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra_password
    volumes:
      - hydra_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - intranet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydra -d hydra"]
      interval: 10s
      timeout: 5s
      retries: 5

  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://kratos:kratos_password@kratos-postgres:5432/kratos?sslmode=disable
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
        read_only: true
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
    depends_on:
      kratos-postgres:
        condition: service_healthy

  # NEW: Hydra database migration
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=postgres://hydra:hydra_password@hydra-postgres:5432/hydra?sslmode=disable
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./config/hydra
        target: /etc/config/hydra
        read_only: true
    restart: on-failure
    networks:
      - intranet
    depends_on:
      hydra-postgres:
        condition: service_healthy

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:kratos_password@kratos-postgres:5432/kratos?sslmode=disable
      - LOG_LEVEL=info
      - GOOGLE_CLIENT_ID=165106799463-ijl47hp8fco7abh6hcsu453lb4kvqjlf.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
        read_only: true
    networks:
      - intranet

  # NEW: Ory Hydra OAuth2/OIDC Server
  hydra:
    depends_on:
      - hydra-migrate
    image: oryd/hydra:v2.2.0
    ports:
      - '4444:4444' # public
      - '4445:4445' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://hydra:hydra_password@hydra-postgres:5432/hydra?sslmode=disable
      - TTL_ACCESS_TOKEN=24h
      - TTL_REFRESH_TOKEN=720h
      - TTL_ID_TOKEN=1h
      - TTL_AUTH_CODE=10m
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - ./config/hydra:/etc/config/hydra:ro
    networks:
      - intranet

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434
      - HYDRA_ADMIN_URL=http://hydra:4445  # NEW: Hydra admin URL
      - HYDRA_PUBLIC_URL=http://hydra:4444  # NEW: Hydra public URL
      - DATABASE_URL=postgres://userms:userms_password@postgres:5432/userms?sslmode=disable
      - PORT=3000
    volumes:
      - ./:/app
      - /app/tmp
    networks:
      - intranet
    depends_on:
      postgres:
        condition: service_healthy
      kratos:
        condition: service_started
      hydra:
        condition: service_started
    restart: unless-stopped
    command: ["./main"]

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://172.16.1.65:3000
      - REACT_APP_KRATOS_PUBLIC_URL=http://172.16.1.65:4433
      - REACT_APP_HYDRA_PUBLIC_URL=http://172.16.1.65:4444  # NEW: Hydra public URL
      - PORT=3001
      - GENERATE_SOURCEMAP=false
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - intranet
    depends_on:
      - kratos
      - hydra
      - backend
    restart: unless-stopped

networks:
  intranet:

volumes:
  postgres_data:
  kratos_postgres_data:
  hydra_postgres_data:  # NEW: Hydra database volume